title: Name Blog
email: a@b.com
description: Meta desc
baseurl: "/"
url: ""
subtitle: Hello! Welcome to
intro: Intro
address: Address
phone: +44 000
logo: 
txt_logo: Name <span>Blog</span>
video: 
cover: cover.jpg
alt_cover: 
maps: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d317718.69319292053!2d-0.3817765050863085!3d51.528307984912544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a00baf21de75%3A0x52963a5addd52a99!2sLondres%2C%20Royaume-Uni!5e0!3m2!1sfr!2spl!4v1590926859506!5m2!1sfr!2spl

comments: true # If true the comments section appear in the posts pages

markdown: kramdown

collections:
  authors:
    default:
      layout: authors
    output: true
  categories:
    output: true

sass:
  style: compressed
  sass_dir: _sass

defaults:
  -
    scope:
      type: posts
    values:
      layout: blog
  -
    scope:
      type: categories
    values:
      layout: categorie
  -
    scope:
      type: authors
    values:
      layout: author
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: /articles/:title/